"""Tables backing document storage and retrieval."""

from datetime import datetime
from typing import Any

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    ARRAY,
    Computed,
    DateTime,
    Index,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, TSVECTOR
from sqlalchemy.orm import Mapped, mapped_column

from paimon.infrastructure.persistence.models.base import Base

EMBEDDING_DIMENSIONS = 1024
"""Fixed platform-wide (ADR-0011).

pgvector indexes the ``vector`` type with HNSW up to 2000 dimensions, and
text-embedding-3-large emits 3072, so the Azure adapter requests 1024 through the
model's dimensions parameter and the local model produces 1024 natively. Changing
this number means a new migration and a full reindex, which is exactly why it is
stated in one place rather than inferred from whatever wrote last.
"""


class DocumentRow(Base):
    """A normalized source document.

    Holds the canonical text that chunk offsets index into, so a citation can be
    resolved back to the passage it points at.
    """

    __tablename__ = "documents"

    tenant_id: Mapped[str] = mapped_column(String(128), primary_key=True)
    document_id: Mapped[str] = mapped_column(String(256), primary_key=True)
    source_uri: Mapped[str] = mapped_column(Text, nullable=False)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    text: Mapped[str] = mapped_column(Text, nullable=False)
    content_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    media_type: Mapped[str] = mapped_column(String(128), nullable=False)
    # What produced the stored chunks: the chunking policy and the embedding
    # model. Content alone cannot decide whether a document needs reindexing —
    # the same bytes chunked at two sizes are two different indexes.
    pipeline_fingerprint: Mapped[str] = mapped_column(
        String(256), nullable=False, server_default=""
    )
    # Named doc_metadata in the database too, not just in Python. A column
    # called "metadata" collides with SQLAlchemy's own MetaData attribute on a
    # declarative class, and the two halves of the ORM disagree about which name
    # to use: values() takes the attribute, excluded takes the column. The fix is
    # to remove the collision rather than to remember it.
    doc_metadata: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, server_default="{}")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (Index("ix_documents_content_hash", "tenant_id", "content_hash"),)


class ChunkRow(Base):
    """A retrievable span of a document, with its embedding.

    There is deliberately no foreign key to ``documents``. Chunks live behind the
    VectorStore port and documents behind the DocumentRepository port, and one
    supported production configuration puts them in different systems entirely —
    Azure AI Search and PostgreSQL. A design that depends on referential
    integrity between the two could not be deployed that way, so the relationship
    is maintained by the ingestion use case instead: it replaces a document's
    chunks before recording the document.
    """

    __tablename__ = "chunks"

    tenant_id: Mapped[str] = mapped_column(String(128), primary_key=True)
    chunk_id: Mapped[str] = mapped_column(String(320), primary_key=True)
    document_id: Mapped[str] = mapped_column(String(256), nullable=False)
    ordinal: Mapped[int] = mapped_column(Integer, nullable=False)
    text: Mapped[str] = mapped_column(Text, nullable=False)
    heading_path: Mapped[list[str]] = mapped_column(
        ARRAY(Text), nullable=False, server_default="{}"
    )
    start_char: Mapped[int] = mapped_column(Integer, nullable=False)
    end_char: Mapped[int] = mapped_column(Integer, nullable=False)
    token_count: Mapped[int] = mapped_column(Integer, nullable=False)
    embedding: Mapped[list[float]] = mapped_column(Vector(EMBEDDING_DIMENSIONS), nullable=False)
    embedding_model: Mapped[str] = mapped_column(String(128), nullable=False)

    # Generated by the database rather than written by the application: a derived
    # column that the application maintains drifts the moment one write path
    # forgets it. Headings are included because a section title is often the only
    # place a term appears.
    #
    # paimon_array_to_string is created by the migration. PostgreSQL requires an
    # IMMUTABLE expression here and array_to_string is only STABLE.
    search_vector: Mapped[str] = mapped_column(
        TSVECTOR,
        Computed(
            "to_tsvector('english', paimon_array_to_string(heading_path, ' ') || ' ' || text)",
            persisted=True,
        ),
        nullable=False,
    )

    __table_args__ = (
        Index("ix_chunks_document", "tenant_id", "document_id"),
        Index("ix_chunks_search_vector", "search_vector", postgresql_using="gin"),
        Index(
            "ix_chunks_embedding_hnsw",
            "embedding",
            postgresql_using="hnsw",
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
    )
